import { SignInButton, useUser } from '@clerk/nextjs';
import { type NextPage } from 'next';
import Head from 'next/head';
import { api } from '~/utils/api';
import Post from '../components/Post';
import CreatePost from '~/components/CreatePost';

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex h-screen justify-center bg-black text-slate-100 antialiased'>
        <div className='w-full border-x border-slate-400 md:max-w-2xl'>
          <div className='border-b border-slate-400 p-4'>
            {!user.isSignedIn && (
              <div className='flex justify-center'>
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && CreatePost(user.user.profileImageUrl)}
          </div>
          <div className='flex flex-col'>
            {isLoading && (
              <div className='flex items-center justify-center p-8'>
                Loading...
              </div>
            )}
            {data?.map(({ post, author }) => (
              <Post key={post.id} post={post} author={author} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
